sudo: required
dist: trusty
language: php

git:
  submodules: false

addons:
  hosts:
    - www.benevaut.fr.local

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - CODECLIMATE=off
        - COMPOSER_FLAGS="--prefer-lowest" # Cover laravel 5.5.x (LTS) vendors
    - php: 7.3
      env:
        - CODECLIMATE=on
        - COMPOSER_FLAGS="" # Cover laravel 6.0.x (LTS) vendors
    - php: 7.4
      env:
        - CODECLIMATE=off
        - COMPOSER_FLAGS="--prefer-lowest" # Cover laravel 5.5.x (LTS) vendors
    - php: 7.4
      env:
        - CODECLIMATE=off
        - COMPOSER_FLAGS="" # Cover laravel 6.0.x (LTS) vendors
    - php: nightly
      env:
        - CODECLIMATE=off
        - COMPOSER_FLAGS="--prefer-lowest" # Cover laravel 5.5.x (LTS) vendors
    - php: nightly
      env:
        - CODECLIMATE=off
        - COMPOSER_FLAGS="" # Cover laravel 6.0.x (LTS) vendors
  allow_failures:
    - php: 7.4
    - php: nightly

before_install:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
    fi

install:
  - travis_retry composer install -o --no-interaction --prefer-dist --no-suggest
  - travis_retry composer update --prefer-source $COMPOSER_FLAGS
  - composer info illuminate/support | grep "versions"

before_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter before-build
    fi

script: composer test

after_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.php.json coverage/clover.xml
      ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
      ./cc-test-reporter upload-coverage
    fi
