language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: composer test
