sudo: required
dist: trusty
language: php

git:
  submodules: false

addons:
  hosts:
    - www.benevaut.fr.local

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - CODECLIMATE=on
    - php: 7.4
      env:
        - CODECLIMATE=off
    - php: nightly
      env:
        - CODECLIMATE=off
  allow_failures:
    - php: 7.4
    - php: nightly

before_install:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
    fi

install:
  - travis_retry composer install -o --no-interaction --prefer-dist --no-suggest

before_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter before-build
    fi

script: composer test

after_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.php.json coverage/clover.xml
      ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
      ./cc-test-reporter upload-coverage
    fi
